logic update for force build 5

diff --git a/templates/deploy-ee.yml b/templates/deploy-ee.yml
--- a/templates/deploy-ee.yml
+++ b/templates/deploy-ee.yml
@@ -6,7 +6,7 @@ parameters:
     default:
       - ee-default
       - ee-linux
-      - ee-aws
+      # - ee-aws
       # - ee-azure
       # - ee-windows
       # - ee-network-cisco
@@ -128,19 +128,19 @@ steps:
             echo "#############################################################"
             echo "## Starting build of EE ${{ EE }} on $(AUTOMATION_HUB_FQDN)"
             echo "#############################################################"
-            # podman login -u "$(CI_RHN_USER)" -p "$(CI_RHN_PASSWORD)" registry.redhat.io
-            # cd exec-env/${{ EE }}
-            # pwd
-            # [[ ! -d ./context ]] && mkdir context
-            # # cp /etc/pki/rpm-gpg/* ./context/
-            # ansible-builder build --tag ${{ EE }}-$(ANSIBLE_VERSION):$(Build.SourceVersion) --container-runtime podman -v 3 --no-cache --prune-image
-            # podman login -u $(AUTOMATION_HUB_USER) -p $(AUTOMATION_HUB_PASS) $(AUTOMATION_HUB_FQDN) --tls-verify=False
-            # podman tag ${{ EE }}-$(ANSIBLE_VERSION):$(Build.SourceVersion) $(AUTOMATION_HUB_FQDN)/${{ EE }}-$(ANSIBLE_VERSION):$(Build.SourceVersion)
-            # podman tag ${{ EE }}-$(ANSIBLE_VERSION):$(Build.SourceVersion) $(AUTOMATION_HUB_FQDN)/${{ EE }}-$(ANSIBLE_VERSION):latest
-            # podman push $(AUTOMATION_HUB_FQDN)/${{ EE }}-$(ANSIBLE_VERSION):$(Build.SourceVersion) --tls-verify=False
-            # podman push $(AUTOMATION_HUB_FQDN)/${{ EE }}-$(ANSIBLE_VERSION):latest --tls-verify=False
-            # echo "#############################################################"
-            # echo "## Performing Cleanup"
-            # echo "#############################################################"
-            # for i in `podman images | grep $(AUTOMATION_HUB_FQDN) | awk {'print $3'}`; do podman rmi $i -f; done || true
-            # for i in `podman images | grep none | awk {'print $3'}`; do podman rmi $i -f; done || true
+            podman login -u "$(CI_RHN_USER)" -p "$(CI_RHN_PASSWORD)" registry.redhat.io
+            cd exec-env/${{ EE }}
+            pwd
+            [[ ! -d ./context ]] && mkdir context
+            # cp /etc/pki/rpm-gpg/* ./context/
+            ansible-builder build --tag ${{ EE }}-$(ANSIBLE_VERSION):$(Build.SourceVersion) --container-runtime podman -v 3 --no-cache --prune-image
+            podman login -u $(AUTOMATION_HUB_USER) -p $(AUTOMATION_HUB_PASS) $(AUTOMATION_HUB_FQDN) --tls-verify=False
+            podman tag ${{ EE }}-$(ANSIBLE_VERSION):$(Build.SourceVersion) $(AUTOMATION_HUB_FQDN)/${{ EE }}-$(ANSIBLE_VERSION):$(Build.SourceVersion)
+            podman tag ${{ EE }}-$(ANSIBLE_VERSION):$(Build.SourceVersion) $(AUTOMATION_HUB_FQDN)/${{ EE }}-$(ANSIBLE_VERSION):latest
+            podman push $(AUTOMATION_HUB_FQDN)/${{ EE }}-$(ANSIBLE_VERSION):$(Build.SourceVersion) --tls-verify=False
+            podman push $(AUTOMATION_HUB_FQDN)/${{ EE }}-$(ANSIBLE_VERSION):latest --tls-verify=False
+            echo "#############################################################"
+            echo "## Performing Cleanup"
+            echo "#############################################################"
+            for i in `podman images | grep $(AUTOMATION_HUB_FQDN) | awk {'print $3'}`; do podman rmi $i -f; done || true
+            for i in `podman images | grep none | awk {'print $3'}`; do podman rmi $i -f; done || true
